name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      - 'deploy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2.2.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f deploy/k8s && kubectl apply -f deploy/k8s-prod
